name: build_database

on:
  # 支持手动触发工作流，并允许指定拉取的分支
  workflow_dispatch:
  # 支持按计划自动触发工作流，每天凌晨 3 点（UTC 时间）执行
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone specific repository
      run: git clone <repository-url> myrepo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up MySQL 8
      uses: microsoft/setup-mysql@v1
      with:
        mysql-version: '8.0'
        mysql-root-password: '123456'

    - name: Create databases
      run: |
        mysql -uroot -p123456 -e "CREATE DATABASE auth CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"
        mysql -uroot -p123456 -e "CREATE DATABASE world CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"
        mysql -uroot -p123456 -e "CREATE DATABASE characters CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"
        mysql -uroot -p123456 -e "CREATE DATABASE playerbots CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"

    - name: Import base SQL files
      run: |
        mysql -uroot -p123456 auth < myrepo/data/sql/base/auth.sql
        mysql -uroot -p123456 world < myrepo/data/sql/base/world.sql
        mysql -uroot -p123456 characters < myrepo/data/sql/base/characters.sql
        mysql -uroot -p123456 playerbots < myrepo/data/sql/base/playerbots.sql

    - name: Import update SQL files
      run: |
        mysql -uroot -p123456 auth < myrepo/data/sql/updates/auth.sql
        mysql -uroot -p123456 world < myrepo/data/sql/updates/world.sql
        mysql -uroot -p123456 characters < myrepo/data/sql/updates/characters.sql
        mysql -uroot -p123456 playerbots < myrepo/data/sql/updates/playerbots.sql

    - name: Export databases
      run: |
        $timestamp = Get-Date -Format "YYYYMMdd"
        $backupFileName = "databases_$timestamp.zip"
        mysqldump -uroot -p123456 auth > auth.sql
        mysqldump -uroot -p123456 world > world.sql
        mysqldump -uroot -p123456 characters > characters.sql
        mysqldump -uroot -p123456 playerbots > playerbots.sql
        Compress-Archive -Path auth.sql,world.sql,characters.sql,playerbots.sql -DestinationPath $backupFileName

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: databases_*.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up old releases
      uses: mjansen/github-purge-releases@v12
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        keep_days: 3
