name: AzerothCore Build

on:
  push:
    branches:
      - main  # 这里可以改为你想要监听的分支

jobs:
  build:
    runs-on: ubuntu - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git for submodule
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone AzerothCore repository
        uses: actions/checkout@v2
        with:
          repository: AzerothCore/AzerothCore  # 替换为你要拉取的仓库
          ref: master  # 替换为你要拉取的分支
          path: AzerothCore

      - name: Install dependencies
        run: |
          sudo apt - get update
          sudo apt - get install - y cmake g++ gcc make git python3 zlib1g - dev libssl - dev libbz2 - dev libreadline - dev libncurses5 - dev libmariadb - client - libs libmariadb - dev unzip

      - name: Build AzerothCore
        working - directory: AzerothCore
        run: |
          mkdir build
          cd build
          cmake..
          make - j$(nproc)

      - name: Create bin folder and copy compiled files
        run: |
          mkdir -p bin
          cp AzerothCore/build/src/server/bin/* bin/

      - name: Compress bin folder
        run: |
          tar - czvf bin_$(date +%Y%m%d).tar.gz bin

      - name: Create Releases
        uses: softprops/action - github - release@v1
        with:
          files: bin_$(date +%Y%m%d).tar.gz
          tag_name: release_$(date +%Y%m%d)
          release_name: Release $(date +%Y%m%d)

      - name: Clean up old releases
        uses: einaregilsson/delete - artifact@v14
        with:
          keep_n: 3
          pattern: bin_*.tar.gz
