name: build_database

on:
  # 支持手动触发
  workflow_dispatch:
  # 支持自动触发，这里设置为每周六凌晨 3 点触发
  schedule:
    - cron: '0 19 * * *'

jobs:
  build_database:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
      # 设置仓库
      azerothcore_url: https://github.com/ganan3917/azerothcore-wotlk.git
      # 设置分支
      azerothcore_branch: Playerbot
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 拉取 AzerothCore 仓库及分支
      - name: Clone AzerothCore
        run: |
          set -e
          git clone -b ${{ env.azerothcore_branch }} ${{ env.azerothcore_url }} azerothcore-wotlk

      # 获取当前日期
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d)"

      # 检查 data 目录是否存在
      - name: Check data directory existence
        run: |
          if [ -d "azerothcore-wotlk/data" ]; then
            echo "Data directory exists."
          else
            echo "Data directory does not exist."
            exit 1
          fi

      # 打包 data 目录
      - name: Compress data directory
        run: |
          set -e
          sudo tar -zcvf data-${{ steps.date.outputs.date }}.tar.gz azerothcore-wotlk/data

      # 上传打包好的 data 文件作为工作流的制品
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-backup-${{ steps.date.outputs.date }}
          path: data-${{ steps.date.outputs.date }}.tar.gz
