name: build_database

on:
  # 支持手动触发工作流，并允许指定拉取的分支
  workflow_dispatch:
  # 支持按计划自动触发工作流，每天凌晨 3 点（UTC 时间）执行
  schedule:
    - cron: '0 3 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL 8
        run: |
          # 下载 MySQL 8 安装包
          Invoke-WebRequest -Uri 'https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-8.0.33.0.msi' -OutFile'mysql-installer.msi'
          # 安装 MySQL 8，设置 root 密码为 123456
          Start-Process -FilePath'msiexec.exe' -ArgumentList '/i mysql-installer.msi /qn MYSQLROOTPASSWORD="123456" ADDLOCAL=Server,ClientTools' -Wait

      - name: Create databases
        env:
          MYSQL_ROOT_PASSWORD: 123456
        run: |
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD -e "CREATE DATABASE auth; CREATE DATABASE world; CREATE DATABASE characters; CREATE DATABASE playerbots;"

      - name: Import base SQL
        env:
          MYSQL_ROOT_PASSWORD: 123456
        run: |
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD auth <./data/sql/base/auth.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD world <./data/sql/base/world.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD characters <./data/sql/base/characters.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD playerbots <./data/sql/base/playerbots.sql

      - name: Import updates SQL
        env:
          MYSQL_ROOT_PASSWORD: 123456
        run: |
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD auth <./data/sql/updates/auth.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD world <./data/sql/updates/world.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD characters <./data/sql/updates/characters.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD playerbots <./data/sql/updates/playerbots.sql

      - name: Export databases
        env:
          MYSQL_ROOT_PASSWORD: 123456
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD auth > auth_$timestamp.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD world > world_$timestamp.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD characters > characters_$timestamp.sql
          & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe" -uroot -p$env:MYSQL_ROOT_PASSWORD playerbots > playerbots_$timestamp.sql

      - name: Create archive
        run: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          $archivePath = "databases_$timestamp.zip"
          [System.IO.Compression.ZipFile]::CreateFromDirectory("$PWD", $archivePath)

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: databases_*.zip
          draft: false
          prerelease: false

      - name: Clean up old releases
        uses: einaregilsson/delete-older-releases@v20
        with:
          max_count: 3
          github_token: ${{ secrets.GITHUB_TOKEN }}
