name: build_database

on:
  # 支持手动触发工作流，并允许指定拉取的分支
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: false
        default: playerbots
  # 支持按计划自动触发工作流，每天凌晨 3 点（UTC 时间）执行
  schedule:
    - cron: '0 3 * * *'

jobs:
  setup-database:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ganan3917azerothcore-wotlk
          ref: playerbots

      - name: Install MySQL 8
        run: |
          sudo apt - get update
          sudo apt - get install - y mysql - server
          sudo systemctl start mysql
          sudo mysql - e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '123456';"
          sudo mysql - e "CREATE DATABASE `auth` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;;"
          sudo mysql - e "CREATE DATABASE `world` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;;"
          sudo mysql - e "CREATE DATABASE `characters` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"
          sudo mysql - e "CREATE DATABASE `playerbots` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci;"

      - name: Import base SQL files
        run: |
          sudo mysql -uroot -p123456 auth < azerothcore/data/sql/base/auth.sql
          sudo mysql -uroot -p123456 world < azerothcore/data/sql/base/world.sql
          sudo mysql -uroot -p123456 characters < azerothcore/data/sql/base/characters.sql
          sudo mysql -uroot -p123456 playerbots < azerothcore/data/sql/base/playerbots.sql

      - name: Import update SQL files
        run: |
          for file in azerothcore/data/sql/updates/*.sql; do
            if [[ $file == *"auth"* ]]; then
              sudo mysql -uroot -p123456 auth < $file
            elif [[ $file == *"world"* ]]; then
              sudo mysql -uroot -p123456 world < $file
            elif [[ $file == *"characters"* ]]; then
              sudo mysql -uroot -p123456 characters < $file
            elif [[ $file == *"playerbots"* ]]; then
              sudo mysql -uroot -p123456 playerbots < $file
            fi
          done

      - name: Export databases
        run: |
          CURRENT_TIME=$(date +%Y%m%d)
          mysqldump -uroot -p123456 auth > auth_$CURRENT_TIME.sql
          mysqldump -uroot -p123456 world > world_$CURRENT_TIME.sql
          mysqldump -uroot -p123456 characters > characters_$CURRENT_TIME.sql
          mysqldump -uroot -p123456 playerbots > playerbots_$CURRENT_TIME.sql
          tar -czvf databases_$CURRENT_TIME.tar.gz auth_$CURRENT_TIME.sql world_$CURRENT_TIME.sql characters_$CURRENT_TIME.sql playerbots_$CURRENT_TIME.sql

      - name: Upload to Release
        uses: actions/upload - release - asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: databases_$CURRENT_TIME.tar.gz
          asset_name: databases_$CURRENT_TIME.tar.gz
          asset_content_type: application/gzip

      - name: Clean up old releases
        uses: ijliao/delete - release - assets@v15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: databases_*.tar.gz
          keep_days: 3
