name: Manual Install MySQL 8.2 on Windows

on:
  workflow_dispatch:

jobs:
  install-mysql:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download MySQL 8.2 ZIP Archive
        shell: powershell
        run: |
          $mysqlDownloadUrl = "https://dev.mysql.com/get/Downloads/MySQL-8.2/mysql-8.2.0-winx64.zip"
          $downloadPath = "$env:TEMP\mysql-8.2.0-winx64.zip"
          Invoke-WebRequest -Uri $mysqlDownloadUrl -OutFile $downloadPath

      - name: Extract MySQL ZIP Archive
        shell: powershell
        run: |
          $extractPath = "C:\mysql-8.2.0"
          Expand-Archive -Path "$env:TEMP\mysql-8.2.0-winx64.zip" -DestinationPath "C:\"
          Rename-Item -Path "C:\mysql-8.2.0-winx64" -NewName $extractPath

      - name: Create my.ini Configuration File
        shell: powershell
        run: |
          $configContent = @"
          [mysqld]
          basedir = C:\mysql-8.2.0
          datadir = C:\mysql-8.2.0\data
          port = 3306
          character-set-server = utf8mb4
          collation-server = utf8mb4_unicode_ci
          [mysql]
          default-character-set = utf8mb4
          "@
          $configContent | Out-File -FilePath "C:\mysql-8.2.0\my.ini" -Encoding UTF8

      - name: Initialize MySQL Data Directory
        shell: powershell
        run: |
          $mysqlBinPath = "C:\mysql-8.2.0\bin"
          & "$mysqlBinPath\mysqld.exe" --initialize-insecure --console

      - name: Install MySQL Service
        shell: powershell
        run: |
          $mysqlBinPath = "C:\mysql-8.2.0\bin"
          & "$mysqlBinPath\mysqld.exe" --install MySQL82

      - name: Start MySQL Service
        shell: powershell
        run: |
          Start-Service -Name MySQL82

      - name: Set Root Password
        shell: powershell
        run: |
          $mysqlBinPath = "C:\mysql-8.2.0\bin"
          $command = "$mysqlBinPath\mysql.exe -u root --execute=\"ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';\""
          Invoke-Expression $command

      - name: Test MySQL Connection
        shell: powershell
        run: |
          $mysqlBinPath = "C:\mysql-8.2.0\bin"
          $command = "$mysqlBinPath\mysql.exe -u root -p123456 -e 'SHOW DATABASES;'"
          Invoke-Expression $command
