name: build_azero_win

# 触发条件，支持手动触发和定期自动触发
on:
  # 手动触发
  workflow_dispatch:
  # 每天凌晨 2 点自动触发
  schedule:
    - cron: '0 2 * * *'

jobs:
  build_azero_win:
    runs-on: windows-2022

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
         run:|
           git clone -b master https://github.com/azerothcore/azerothcore-wotlk.git

      # 安装 Visual Studio 2022
      - name: Install Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.0'

      # 安装 CMake 3.3
      - name: Install CMake 3.3
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '3.3'

      # 安装 Boost 1.8
      - name: Install Boost 1.8
        run: |
          choco install boost-msvc-14.3 -y --version=1.80.0
          echo "BOOST_ROOT=C:\local\boost_1_80_0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # 安装 MySQL 8.0
      - name: Install MySQL 8.0
        run: |
          choco install mysql -y --version=8.0.26
          echo "MYSQL_DIR=C:\Program Files\MySQL\MySQL Server 8.0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # 安装 OpenSSL 3.2
      - name: Install OpenSSL 3.2
        run: |
          choco install openssl -y --version=3.2.0
          echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # 配置项目
      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64

      # 编译项目
      - name: Compile project
        run: |
          cd build
          msbuild azetothcore.sln /p:Configuration=Release /p:Platform=x64

      # 上传编译结果
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: azetothcore-wotlk-compiled
          path: build/Release
