name: build_azerothcore

on:
  # 支持手动触发
  workflow_dispatch:
  push:
    branches:
      - playerbot

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出 AzerothCore 源代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Visual Studio 环境
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1

      # 安装 CMake
      - name: Install CMake
        uses: lukka/get-cmake@latest

      # 安装 Git
      - name: Install Git
        run: choco install -y git

      # 安装 MySQL
      - name: Install MySQL
        run: |
          choco install -y mysql --version=8.0.28
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          mysqld --initialize-insecure
          Start-Service MySQL80
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';"

      # 安装 OpenSSL
      - name: Install OpenSSL
        run: choco install -y openssl

      # 安装 Boost
      - name: Install Boost
        run: |
          choco install -y boost-msvc-14.3
          $env:BOOST_ROOT = "C:\local\boost_1_76_0"  # 根据实际安装路径调整
          [System.Environment]::SetEnvironmentVariable("BOOST_ROOT", $env:BOOST_ROOT, [System.EnvironmentVariableTarget]::Machine)

      # 配置和编译 AzerothCore
      - name: Configure and build AzerothCore
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 ..
          msbuild AzerothCore.sln /p:Configuration=Release /p:Platform=x64
