name: Delete_old_workflow

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点执行

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAYS_TO_KEEP: 3
        run: |
          # 获取仓库的所有者和名称
          OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
          REPO=$(echo ${{ github.repository }} | cut -d '/' -f 2)

          # 获取当前日期
          CURRENT_DATE=$(date +%Y-%m-%d)

          # 计算 3 天前的日期
          THREE_DAYS_AGO=$(date -d "$CURRENT_DATE - $DAYS_TO_KEEP days" +%Y-%m-%d)

          # 获取所有工作流 ID
          WORKFLOW_IDS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/workflows" | jq -r '.workflows[].id')

          # 遍历每个工作流 ID
          for WORKFLOW_ID in $WORKFLOW_IDS; do
            # 获取该工作流的所有运行记录
            RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/runs" | jq -r '.workflow_runs[] | select(.created_at < "'$THREE_DAYS_AGO'T00:00:00Z") | .id')

            # 遍历符合条件的运行记录 ID 并删除
            for RUN_ID in $RUNS; do
              echo "Deleting workflow run $RUN_ID for workflow $WORKFLOW_ID"
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID"
            done
          done
