name: Delete_old_workflow

on:
  # 手动触发，通过 GitHub 界面的 Actions 选项卡中的 "Run workflow" 按钮触发
  workflow_dispatch:
  # 定时触发，每 3 天执行一次
  schedule:
    - cron: '0 5 */3 * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old runs for all workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 保留每个工作流最新的运行记录数量
          KEEP_LATEST: 3 
        run: |
          echo "Starting to clean up old runs for all workflows."
          # 获取仓库中所有工作流
          WORKFLOWS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | \
            jq -r '.workflows[].id')

          for WORKFLOW_ID in $WORKFLOWS; do
            echo "Processing workflow with ID: $WORKFLOW_ID"
            # 获取当前工作流的所有运行记录
            RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?per_page=100" | \
              jq -r '.workflow_runs[].id')

            # 将运行记录 ID 存储到数组中
            IDS=($RUNS)
            # 计算需要删除的运行记录数量
            DELETE_COUNT=$(( ${#IDS[@]} - $KEEP_LATEST ))

            if [ $DELETE_COUNT -gt 0 ]; then
              for ((i = 0; i < $DELETE_COUNT; i++)); do
                RUN_ID=${IDS[$i]}
                echo "Deleting run with ID: $RUN_ID"
                # 调用 API 删除运行记录
                curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
              done
            else
              echo "No runs to delete for workflow with ID: $WORKFLOW_ID."
            fi
          done
          echo "Finished cleaning up old runs for all workflows."
